version: "2"
services:
  arduino-cli:
    container_name: platformio-core
    # image: platformio-core
    # Build lively
    build: .
    volumes:
      - /home/pi/docker_files/platformio-core/library:/root/.platformio
      - /home/pi/docker_files/platformio-core/workspace:/workspace
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
